name: Simple Sleep Workflow

on: [push]

jobs:
  sleep_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run sleep command
      run: |
        echo "Starting sleep command..."
        sleep 10 && exit 1
        echo "Sleep command finished."
